/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.List;
import java.util.Vector;

/**
 * Klasa obrazuje formatkę Zarządzania konferencją
 */
public class ConferenceFrame extends javax.swing.JFrame {
    ApplicationFrame application;
    Vector<String> availableUsersTab;
    Vector<String> selectedUsersTab;
    
    public static final int CONFERENCE_TYPE_TEXT = 1;
    public static final int CONFERENCE_TYPE_VIDEO = 0;
    private int selectedConferenceType;
    private boolean isNewConference = true;
    
    public ConferenceFrame() {
        initComponents();
    }
    
    public ConferenceFrame(ApplicationFrame app) {
        initComponents();
        
        this.application = app;
        
        this.setAvailableUserList(this.application.getApplicationComponents().getLoginController().getContacts());
        selectedUsersTab = new Vector<String>();
    }
    
    public void modifyConference(){
        this.conferenceType.setEnabled(false);
        this.startVideoConferenceBtn.setText("Zastosuj");
        this.isNewConference = false;
        this.setVisible(true);
    }
    
    public void setAvailableUserList(List<Entities.Contacts> userslist){
        if (userslist != null) {
            availableUsersTab = new Vector<String>();
            for (int i = 0; i < userslist.size(); i++) {
                availableUsersTab.add(userslist.get(i).getName().toString());
            }
            
            this.avialabeUsers.setListData(availableUsersTab);
        }
    }
    
    public String[] getUsersListToConference(){
           String[] list = new String[this.selectedUsers.getModel().getSize()];
           for(int i = 0; i < this.selectedUsers.getModel().getSize(); i++)
               list[i] = (String)this.selectedUsers.getModel().getElementAt(i);
           
           return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        avialabeUsers = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        addUserBtn = new javax.swing.JButton();
        removeUserBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedUsers = new javax.swing.JList();
        conferenceType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        startVideoConferenceBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Wybierz uczestników konferencji");

        avialabeUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        avialabeUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avialabeUsersMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                avialabeUsersMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(avialabeUsers);

        jLabel2.setText("Dostępni uczestnicy");

        addUserBtn.setText("Dodaj >");
        addUserBtn.setEnabled(false);
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        removeUserBtn.setText("< Usuń");
        removeUserBtn.setEnabled(false);
        removeUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserBtnActionPerformed(evt);
            }
        });

        selectedUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        selectedUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectedUsersMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectedUsersMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(selectedUsers);

        conferenceType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wideokonferencja", "Konferencja tekstowa" }));

        jLabel3.setText("Rodzaj konferencji:");

        startVideoConferenceBtn.setText("Rozpocznij");
        startVideoConferenceBtn.setEnabled(false);
        startVideoConferenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startVideoConferenceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conferenceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(removeUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(startVideoConferenceBtn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(addUserBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeUserBtn)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(conferenceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(startVideoConferenceBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserBtnActionPerformed
        if(this.selectedUsers.getSelectedIndex() > -1){
            availableUsersTab.add(selectedUsersTab.get(this.selectedUsers.getSelectedIndex()));
            selectedUsersTab.remove(this.selectedUsers.getSelectedIndex());
            
            this.selectedUsers.setListData(selectedUsersTab);
            this.avialabeUsers.setListData(availableUsersTab);
            
            addUserBtn.setEnabled(avialabeUsers.getModel().getSize() > 0 && avialabeUsers.getSelectedIndex() > -1);
            removeUserBtn.setEnabled(selectedUsers.getModel().getSize() > 0 && selectedUsers.getSelectedIndex() > -1);
            
            startVideoConferenceBtn.setEnabled(selectedUsers.getModel().getSize() > 0);
        }
    }//GEN-LAST:event_removeUserBtnActionPerformed

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        if(this.avialabeUsers.getSelectedIndex() > -1){
            selectedUsersTab.add(availableUsersTab.get(this.avialabeUsers.getSelectedIndex()));
            availableUsersTab.remove(this.avialabeUsers.getSelectedIndex());
            
            this.selectedUsers.setListData(selectedUsersTab);
            this.avialabeUsers.setListData(availableUsersTab);
            
            addUserBtn.setEnabled(avialabeUsers.getModel().getSize() > 0 && avialabeUsers.getSelectedIndex() > -1);
            removeUserBtn.setEnabled(selectedUsers.getModel().getSize() > 0 && selectedUsers.getSelectedIndex() > -1);
            
            startVideoConferenceBtn.setEnabled(selectedUsers.getModel().getSize() > 0);
        }
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void selectedUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedUsersMouseClicked
        //if(this.selectedUsers.getSelectedIndex() > -1){
        //    removeUserBtn.setEnabled(true);
        //}
    }//GEN-LAST:event_selectedUsersMouseClicked

    private void avialabeUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avialabeUsersMouseClicked
        //if(this.avialabeUsers.getSelectedIndex() > -1){
        //    addUserBtn.setEnabled(true);
        //}
    }//GEN-LAST:event_avialabeUsersMouseClicked

    private void avialabeUsersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avialabeUsersMouseReleased
        if(this.avialabeUsers.getSelectedIndex() > -1){
            addUserBtn.setEnabled(true);
        }
    }//GEN-LAST:event_avialabeUsersMouseReleased

    private void selectedUsersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedUsersMouseReleased
        if(this.selectedUsers.getSelectedIndex() > -1){
            removeUserBtn.setEnabled(true);
        }
    }//GEN-LAST:event_selectedUsersMouseReleased

    private void startVideoConferenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startVideoConferenceBtnActionPerformed
        if(this.isNewConference){
            this.selectedConferenceType = this.conferenceType.getSelectedIndex();
            
            this.setVisible(false);
            
            if(this.selectedConferenceType == CONFERENCE_TYPE_TEXT){
                MessegerFrame msgr = new MessegerFrame(this);
                msgr.setLocationRelativeTo(msgr.getRootPane());
                msgr.setVisible(true);
            }
        }else{
            this.setVisible(false);
        }
    }//GEN-LAST:event_startVideoConferenceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConferenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConferenceFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBtn;
    private javax.swing.JList avialabeUsers;
    private javax.swing.JComboBox conferenceType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeUserBtn;
    private javax.swing.JList selectedUsers;
    private javax.swing.JButton startVideoConferenceBtn;
    // End of variables declaration//GEN-END:variables
}
